### ISSUE TITLE
Connection with wearable device

### ISSUE THREAD

**Issue by shin2jhoon** [pocmo/SensorDashboard#5]
I have some question. 

When I download application at playstore, then It can connect with wearable device, so get data from it.
but when I download this code and run it, but it cannot connect with wearable device.

I want to develop some application with this code, but I can't test .

**Comment by pocmo** [comment]
Hi there! When compiling the code yourself you'll need to build two apks (app & wear) and deploy them to the mobile phone AND the watch yourself. Just deploying the phone app will not install the wear part on the watch.

**Comment by shin2jhoon** [comment]
Ah! Thank you. I'll try and then if I can't success, I'll question to you again.

Thank you very much~!!

**Comment by shin2jhoon** [comment]
Ah, But There are message that, when I build wear
'Default Activity not found' T.T

**Comment by pocmo** [comment]
Your Run Configuration is probably set to "Launch default Activity" in Android Studio. The wear app does not contain any activities. Just select "Do not launch Activity".

**Comment by shin2jhoon** [comment]
Wow you are genius. 
Thank you very much. I'm newbie developing wearable device.
Thank Thank Thank you~~!!!

**Comment by pocmo** [comment]
Have fun with the code. :)

**Comment by shin2jhoon** [comment]
Can I have one more question.
I follow your guide, build each of phone and wearable device. 
So I can run application at both, but it seems that data can't transfer wearable device to phone.
Log shows that wearable device collecting data, but Phone application only show 'waiting for sensor input from a wearable..'

![fullsizerender 1](https://cloud.githubusercontent.com/assets/4902370/7650403/dacb763a-fb30-11e4-9f3b-90ef46f288b2.jpg)
![fullsizerender](https://cloud.githubusercontent.com/assets/4902370/7650404/dad3a530-fb30-11e4-8436-a56c4122028a.jpg)

**Comment by pocmo** [comment]
We are using the synchronization API of the Google Play Service for transfering the sensor data from the wearable to the device. Maybe your device is changing the data too fast so that the synchronization actually never starts.
We are throttling sending sensor data for the currently visible sensor on the phone (faster) and all other sensors (slower) here:
https://github.com/pocmo/SensorDashboard/blob/master/wear/src/main/java/com/github/pocmo/sensordashboard/DeviceClient.java#L64

Try adjusting these values. We never ran the code on a LG-R watch, so maybe they need to be send slower there. Just try sending values veeeery slooooow and see if anything shows up on the phone.

**Comment by shin2jhoon** [comment]
I'll try again. Hmm
By any chance, "Google Play services out of date.  Requires 7327000 but found 7095534" can be the reason of the proplem?

**Comment by ramvibhakar** [comment]
Can someone tell me how to fix this issue? I am getting "Waiting for sensor input from wearable" but Galaxy gear live says "Sensor Dashboard Collecting sensor data"

**Comment by thebino** [comment]
Couldn't find any issues. deploy first the wearable app on the watch.
@ramvibhakar: Do you see any logs from 'MessageReceiverService' on the wearable?
@shin2jhoon: Tried 'play-services-wearable:7.5.0' worked fine, too
